services:
  web:
    image: httpd
    ports:
      - "80:80"
    volumes:
      - ./www:/usr/local/apache2/htdocs
    networks : 
      - default
  dev:
    image: node:alpine
    volumes:
      - ./:/home/node/app
      - ./Docker/node/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh
    working_dir: /home/node/app
    command: "npm run dev"